### PR TITLE
Support for manually closing connection to the database. Resolves #1

### LINKED ISSUE #1: Can't close connection
Is there a way to close a connection manually after performing a query? Looking through the source code, I don't see any way to access the underlying client or any public methods to close the connection. I might be looking in the wrong place, though.

### PR DESCRIPTION
**Pull request by webnard**

### CODE REVIEW

**Comment by jhurliman** [comment]
It looks like this was never merged? Was there a reason for leaving it out?

**Comment by webnard** [comment]
@jhurliman -- it ended up being unnecessary. I had misunderstood how node-postgres-gen functions. Here's what @evs-chris says on the linked issue:

> You can turn off pooling and the connection will automatically be closed at a transactional boundary. So for a single statement, it would open a connection, run the query, and close the connection. For transactions, once the transaction is closed, the connection will also be closed.

**Comment by jhurliman** [comment]
In my case I don't want to disable pooling; I want the application to use pooling but also support a shutdown sequence that closes all connections in the pool. This is something the upstream `node-postgres` library supports and it would be good to expose that functionality in this library.

As a side note, I tested the part about transactions closing their connection and that only seems to hold true when pooling is disabled. With pooling enabled a transaction was still leaving the connection open. Repro code below.

```
import pg from 'postgres-gen'

const DB_URI = 'postgres://...'
const client = pg({ string: DB_URI, pool: true })

function testTransaction () {
  return client.transaction(function *(t) {
    return (yield t.query`select 1 as a`).rows[0]
  })
}

async function main () {
  console.dir(await testTransaction())
  // this program will hang open after printing { a: 1 } to the console
}

main()
```

**Comment by evs-chris** [comment]
@jhurliman the part about transactions closing their connection was meant to be attached to the `pooling: false` statement. So generally, you couldn't control when connections closed unless pooling was disabled.

However, I have just published `0.9.0` which exposes the node-postgres module, should you need it, and adds helper methods that can close the connections for one or all instances. See the bottom of the README.md for more details. Does that handle your use-case?

**Comment by evs-chris** [comment]
Oh, and in the very unlikely event that anyone else should happen upon this, the relevant issue is #1 :smile:

**Comment by jhurliman** [comment]
Perfect, thanks!

**Pull request closed without merging**
